name             'emc'
maintainer       'YOUR_COMPANY_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures emc'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends 'httpd', '~> 0.2'
depends 'yum','~>0.0'
depends 'mysql', '~> 6.0'
